version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: db_bookingroom
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abcd1717
      MYSQL_DATABASE: booking_room
      MYSQL_USER: admin
      MYSQL_PASSWORD: abcd1717
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
